### ISSUE TITLE
The only possible children of <Table>, are <Thead>, <Tr>, or one <Tfoot>.

### ISSUE THREAD

**Issue by fullc0ntr0l** [glittershark/reactable#270]
`The only possible children of <Table>, are <Thead>, <Tr>, or one <Tfoot>.`
I'm getting the follow line in the console every time my component is rendered. 
my table is like this: 
```
<Table>
     <Thead>
        <Th></Th> (more of them)
     </Thead>
    {this.state.rows.map(function)} which returns many <Tr><Td></Td></Tr> elements
</Table>
```

how can I get rid of these console warnings?

**Comment by glittershark** [comment]
Fixed as of 0.13.0

**Comment by paddotk** [comment]
I have Reactable 0.14.0 but still see this error, even though my tag structure is correct (not using Thead but just Tr's in my table).
When I add Thead to the row with Th's, I get `Uncaught TypeError: column.key.replace is not a function` instead. What's going on here?

Also, what happened to Tbody? Has this taken out of Reactable?
